### ISSUE TITLE
paper recommendation

### ISSUE THREAD

**Issue by Jeryi-Sun** [MLNLP-World/Awesome-LLM#4]
Hello! Our new work titled ‘Uncovering ChatGPT’s Capabilities in Recommender Systems’ has been released and can be found at https://arxiv.org/pdf/2305.02182.pdf. We have also open-sourced our code and detailed results at https://github.com/rainym00d/LLM4RS. We kindly request that you add it to this repository. Thank you!

**Comment by yizhen20133868** [comment]
@Jeryi-Sun thanks for your kind recommendation. We will update it soon.

**Comment by Jeryi-Sun** [comment]
Thanks for your update! However, the authors are incomplete. The complete author list at below:
Sunhao Dai, Ninglu Shao, Haiyuan Zhao, Weijie Yu, Zihua Si, Chen Xu, Zhongxiang Sun, Xiao Zhang, Jun Xu
thanks!
