### ISSUE TITLE
Add new paper

### ISSUE THREAD

**Issue by zwhe99** [MLNLP-World/Awesome-LLM#5]
Thanks for your amazing collections!

I would like to recommend our new preprint working on LLM-based translation😁. We explore the capability of LLM to mimic human translation strategy in this paper.

Title: Exploring Human-Like Translation Strategy with Large Language Models
Arxiv: [https://arxiv.org/abs/2305.04118](https://arxiv.org/abs/2305.04118)
Code: [https://github.com/zwhe99/MAPS-mt](https://github.com/zwhe99/MAPS-mt)

**Comment by yizhen20133868** [comment]
@zwhe99 thanks for your recommendation. You can directly give a PR:)

**Comment by zwhe99** [comment]
@yizhen20133868 Hi, I have created a PR here #6.
